package io.banking.whatsapp.accounts.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a transaction in the banking system. This class maps to the
 * 'transactions' collection in MongoDB and includes all necessary fields to
 * track financial transactions.
 *
 * @author Marcelo Alejandro Albarracín
 * @email marceloalejandro.albarracin@gmail.com
 * @version 1.0.0
 * @since 2024-03-19
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "transactions")
public class Transaction {

	/**
	 * The unique identifier for the transaction. Automatically generated by
	 * MongoDB.
	 */
	@Id
	private String id;

	/**
	 * The ID of the account associated with this transaction. References the
	 * Account entity.
	 */
	private String accountId;

	/**
	 * The type of transaction.
	 * 
	 * @see TransactionType
	 */
	private TransactionType type;

	/**
	 * The monetary amount of the transaction.
	 */
	private BigDecimal amount;

	/**
	 * A description of the transaction.
	 */
	private String description;

	/**
	 * A reference code for the transaction. Could be used for external system
	 * references or tracking.
	 */
	private String reference;

	/**
	 * The date and time when the transaction occurred.
	 */
	private LocalDateTime transactionDate;

	/**
	 * The current status of the transaction.
	 * 
	 * @see TransactionStatus
	 */
	private TransactionStatus status;
}